name: Dependabot Automerge - Action

on:
  pull_request:

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy basic-postgres for tests if not exists
        run: >-
          docker container inspect basic-postgres >/dev/null ||
          docker run -d -p 127.0.0.1:5432:5432 --name basic-postgres 
          --restart always -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD 
          -it postgres:14.1-alpine
      - name: Display go.mod
        run: |
          cat go.mod
          git rev-parse --abbrev-ref HEAD
          exit 1
      - name: Run tests
        run: |
          go test -v $PWD/go
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{ secrets.TOKEN }}
