name: Dependabot Automerge - Action

on:
  pull_request:

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy basic-postgres for tests if not exists
        run: >-
          docker rm -f basic-postgres &&
          docker run -d -p 127.0.0.1:5432:5432 --name basic-postgres 
          --restart always -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD 
          -it postgres:14.1-alpine
      - name: Run tests
        run: |
          bash -c 'while !</dev/tcp/127.0.0.1/5432; do sleep 1; done'
          sleep 2
          PGPASSWORD=$POSTGRES_PASSWORD psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE docker;"
          PGPASSWORD=$POSTGRES_PASSWORD psql -h 127.0.0.1 -U postgres -f $PWD/db/init.sql
          /usr/local/go/bin/go test -v $PWD/go
  worker:
    needs: tests
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{ secrets.TOKEN }}
