name: Build & Deploy

on:
  push:
    branches:
      - master
    paths-ignore:  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      run: |
        now=$(date +%Y-%m-%d-%H-%M-%S)
        echo "IMAGE_VERSION_API=${{ secrets.DOCKERHUB_USERNAME }}/llilgq_api:$now" >> $GITHUB_ENV
        echo "IMAGE_VERSION_FRONT=${{ secrets.DOCKERHUB_USERNAME }}/llilgq_front:$now" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        docker-compose build
        docker tag llilgq_api ${{ env.IMAGE_VERSION_API }} 
        docker tag llilgq_front ${{ env.IMAGE_VERSION_FRONT }}
    - name: Push API
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.IMAGE_VERSION_API }}
    - name: Push Front
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.IMAGE_VERSION_FRONT }}
    - name: Set artifact
      run: |
        echo ${{ env.IMAGE_VERSION_API }} > version_api.txt
        echo ${{ env.IMAGE_VERSION_FRONT }} > version_front.txt
    - uses: actions/upload-artifact@v2
      with:
        name: image-version
        path: version.txt
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          docker-compose build --no-cache
          docker-compose up -d